name: Test Workflow

on:
  pull_request:
    types: 
      -opened
      -closed

 
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: download code into server
        uses: actions/checkout@v3

      - name: setting up nodejs
        uses: actions/setup-node@v4
        with:
          version: 22
      - name: installing dependies
        run: npm ci
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: download code into server
        uses: actions/checkout@v3

      - name: setting up nodejs
        uses: actions/setup-node@v4
        with:
          version: 22
      - name: installing dependies
        run: npm ci
      - name: building the app
        run : npm run build
  deploy:
    needs: build
    
    runs-on: ubuntu-latest

    steps:
      - name: download code into server
        uses: actions/checkout@v3

      - name: setting up nodejs
        uses: actions/setup-node@v4
        with:
          version: 22
      - name: deploying into server
        run: |
          echo "It is done"
          echo "It is  not done"

