name: Test Workflow

on:
  push:
    braches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: download code into server
        uses: actions/checkout@v3

      - name: setting up nodejs
        uses: actions/setup-node@v4
        with:
          version: 22
      - name: installing dependies
        run: npm ci
